spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa_ex1?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
server:
  port: 8081